### PR TITLE
Improve instrumentation

### PR DESCRIPTION
**Pull request by asldevi**
- add Jaeger trace propagator
- add Redis instrumentation
- improve PDO and curl instrumentation
- improve error instrumentation
- add ability to pass root span name along with other options while creating trace
- use span attribute names like db.type, db.statement etc as suggested by https://opentracing.io/specification/conventions/

### CODE REVIEW

**Comment by nenad** [comment]
Hey @asldevi, thanks for your contribution! Would you mind pushing a dummy commit so that the CI tests run? I just updated the CircleCI project to run the build on fork PRs as well, for some reason it was off.

**Comment by asldevi** [comment]
@nenad we're observing a memory bloat  with [PDO's instrumentation|https://github.com/nenad/opencensus-php/blob/master/src/Trace/Integrations/PDO.php#L102]. Have you or anyone else faced this issue before? (Excuse me for asking here in the PR comments.)

**Comment by nenad** [comment]
Hey @asldevi. I've taken this from the original OpenCensus repo as-is, and our team didn't have a need for this integration so I don't have any experience with it. I would be happy to accept a patch if you figure out what is causing the bloat in this library. :)

**Comment by nenad** [comment]
Folks, I'll close this PR as I can see now you are using your forked version. Nice work!

**Comment by asldevi** [comment]
hey @nenad, yes we have forked the repo. But would like to contribute back if there is any active development happening or foreseen on this fork, so that the community would benefit by having one single thing. Do let us know.

**Comment by nenad** [comment]
@asldevi There isn't active development happening on this repo or any work planned. If you'd prefer, I could point out this in the README and point to your fork instead.

**Comment by asldevi** [comment]
@nenad that'd be awesome, both to us and community. Thanks in advance.

**Comment by nenad** [comment]
Done. Good luck!

**Pull request closed without merging**
